name: Sync to py3 branch
on:
  push:
    branches:
      - master
jobs:
  makepr:
    name: Generate PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge with py3
        run: |
          git fetch origin py3
          git checkout origin/py3 -b py3-sync
          git config --global user.email "bot@chirp.danplanet.com"
          git config --global user.name "Merge Bot"
          git merge $GITHUB_SHA --allow-unrelated-histories --no-edit || {
            git add -u
            git commit --no-edit
          }
          git checkout -b auto-py3-$GITHUB_SHA
      - name: Update support matrix if needed
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip python3-wxgtk4.0
          sudo python3 -mpip install tox
          tox -e makesupported || git commit -m "Update support matrix" tests/Python3_Driver_Testing.md
      - name: Push changes
        run: |
          git push origin auto-py3-$GITHUB_SHA:auto-py3-$GITHUB_SHA
      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PR_SYNC }}
          source_branch: auto-py3-${{ github.sha }}
          destination_branch: py3
          pr_title: "[Automated] Sync master with py3"
          pr_body: "Automated pull request to sync py3 with changes from master"
