name: Test
on:
  pull_request:
  push:
jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get remove -y python3-libxml2
          sudo apt-get install -y libxml2-dev python-dev python-libxml2
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
          python get-pip.py
          pip --version
          python -m pip install --upgrade --no-deps --force-reinstall lxml
          python -m pip install \
            future \
            pep8 \
            pyserial \
            tox
      - run: tox
